//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDS.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodDistribution
    {
        public int DistributionId { get; set; }
        public int BenId { get; set; }
        public string FoodItem { get; set; }
        public Nullable<System.DateTime> DisDate { get; set; }
        public Nullable<int> DisQuantity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> StoreId { get; set; }
    
        public virtual Beneficiary Beneficiary { get; set; }
        public virtual FoodStore FoodStore { get; set; }
    }
}
