//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDS.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodStore()
        {
            this.Donations = new HashSet<Donation>();
            this.FoodDistributions = new HashSet<FoodDistribution>();
        }
    
        public int StoreId { get; set; }
        public string StoreName { get; set; }
        public int StoreCapacity { get; set; }
        public string StoreLocation { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> Available { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodDistribution> FoodDistributions { get; set; }
    }
}
